name: Android CI - Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Give execute permission to gradlew
        run: chmod +x gradlew

      - name: Build the Project
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew test
